# Generated by Django 5.1.2 on 2024-10-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable_generator.login')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable_generator.login')),
            ],
        ),
    ]
