# Generated by Django 5.1.2 on 2024-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0003_rename_user_student_name_alter_faculty_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=40)),
                ('dept_id', models.CharField(max_length=40)),
            ],
        ),
    ]
