# Generated by Django 5.1.2 on 2024-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0005_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=40)),
                ('dept_id', models.CharField(max_length=40)),
                ('sem_name', models.CharField(max_length=40)),
            ],
        ),
    ]
