# Generated by Django 5.1.2 on 2024-11-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0006_majors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Faculty', 'Faculty'), ('hod', 'hod')], max_length=40),
        ),
    ]
