# Generated by Django 5.1.2 on 2024-11-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0007_alter_login_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Majors',
        ),
    ]
